### ISSUE TITLE
Hero carousel slider never activated on desktop >= 2.15.0

### ISSUE THREAD

**Issue by seyuf** [magesuite/content-constructor-frontend#1]
Since v 2.15.0 after setting up the hero carousel on a cms page, the slider is never activated on desktop.
It looks like *teaserWidth* is always set to 0 in `vendor/creativestyle/magesuite-content-constructor-frontend/view/frontend/templates/component/image_teaser.phtml` `$teaserWidth = $imageTeaser['scenario']['teaserWidth']['id'];`. As it is not possible to set this from the admin should this be considered a bug?

Thanks

**Comment by berbua** [comment]
Hello seyuf, thanks for reaching us. _teaserWidth_ is set in `/src/etc/view.xml`:
```
<var name="hero_carousel">
    <var name="additional_css_classes">cs-hero--centered</var>
    <var name="teaser_width">container-slider</var>
```
Default value for _teaserWidth_ is _container-slider_, but it can be also set to _window-slider_.
Could you please check if you are using actual version of the XML and proper vars are in place?

Kind regards,
Kasia

**Comment by seyuf** [comment]
Hi berbua,
That seems to indeed solve the issue. 
But the variable seems to not be set by default though, i am using magesuite v3.0.0.
In any case i am closing this.

Thanks
