### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Undefined class constant 'CURRENT_BRAND' 

### ISSUE THREAD

**Issue by groomershop-mt** [magesuite/content-constructor-frontend#5]
After update from v2.22.1 to v2.22.2 we get an 500 error:
Probably changed the magesuite/brand-management has not been published.

2020-08-26 18:49:07.222816 [NOTICE] [22728] [213.180.203.118:40338#APVH_www.nowy.groomershop.pl:443] [STDERR] PHP Fatal error:  Uncaught Error: Undefined class constant 'CURRENT_BRAND' in /home/magento/domains/nowy.groomershop.pl/public_html/vendor/creativestyle/magesuite-content-constructor-frontend/Observer/AddConstructorContentToBrandLayout.php:29
Stack trace:
#0 /home/magento/domains/nowy.groomershop.pl/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): MageSuite\ContentConstructorFrontend\Observer\AddConstructorContentToBrandLayout->execute(Object(Magento\Framework\Event\Observer))
#1 /home/magento/domains/nowy.groomershop.pl/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(MageSuite\ContentConstructorFrontend\Observer\AddConstructorContentToBrandLayout), Object(Magento\Framework\Event\Observer))
#2 /home/magento/domains/nowy.groomershop.pl/public_html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#3  in /home/magento/domains/nowy.groomershop.pl/public_html/vendor/creativestyle/magesuite-content-constructor-frontend/Observer/AddConstructorContentToBrandLayout.php on line 29

**Comment by diwipl** [comment]
Just to clarify what happened, we had some issues with github.com synchronisation. Code was pushed to github but packagist did not updated version after the push automatically.

I've updated package manually.

**Comment by groomershop-mt** [comment]
Yes, thank you. We have later saw updated magesuite brand component, which solves this error.
